vars:
  - data_raw: data/Raw
  - data_prepared: data/Prepared
  - data_eval: data/Eval

stages:
  get_data:
    cmd: bash scripts/get_data.sh
    outs:
      - data/Raw/Folsom_irradiance.csv
      - data/Raw/images/:
          cache: false

  convert_timestamps:
    cmd: python ${convert_timestamps.script_path}
         --data-raw ${data_raw}
         --output-path ${convert_timestamps.output_path}
    deps:
      - ${data_raw}/images/
      - ${convert_timestamps.script_path}
    outs:
      - ${convert_timestamps.output_path}

  clean_dataframe:
    cmd: python ${clean_dataframe.script_path}
         --data-raw ${data_raw}
         --images-path ${convert_timestamps.output_path}
         --output-path ${clean_dataframe.output_path}
    deps:
      - ${data_raw}/Folsom_irradiance.csv
      - ${convert_timestamps.output_path}
      - ${clean_dataframe.script_path}
    outs:
      - ${clean_dataframe.output_path}

  export_periods:
    cmd: python ${export_periods.script_path}
         --cleaned-dataframe-path ${clean_dataframe.output_path}
         --time-window ${export_periods.time_window}
         --history-size ${export_periods.history_size}
         --output-path ${export_periods.output_path}
    deps:
      - ${export_periods.script_path}
      - ${clean_dataframe.output_path}
    params:
      - export_periods.time_window
      - export_periods.history_size
    outs:
      - ${export_periods.output_path}

  export_eval_periods:
    cmd: python ${export_eval_periods.script_path}
         --data-prepared-path ${data_prepared}
         --output-path ${export_eval_periods.output_path}
    deps:
      - ${data_prepared}/images/
      - ${export_periods.output_path}
      - ${export_eval_periods.script_path}
    outs:
      - ${export_eval_periods.output_path}

  train_forecaster:
    cmd: python ${train_forecaster.script_path}
         --data-root ${data_prepared}
    deps:
      - ${train_forecaster.script_path}
      - ${data_prepared}
      - ${export_periods.output_path}
      - src/solar_irradiance/models/forecaster.py
    params:
      - train_forecaster
