clean_dataframe:
  script_path: scripts/prepare_dataframe.py
  output_path: data/Prepared/cleaned_irradiance.csv

export_periods:
    script_path: scripts/export_folsom.py
    time_window: 15
    history_size: 3
    output_path: data/Prepared/periods.pickle

train_forecaster:
  script_path: scripts/train_forecaster.py
  seed: 42

  #### MODE ####
  debug: False
  test_only: False

  restore_from_ckpt:

  export:
    export_to_onnx: False
    opset: 15
    use_simplifier: False

  #### TRAINER ####
  trainer:
    devices: 1
    precision: bf16-mixed
    max_epochs: 1000

  #### MODEL ####
  model:
    model_name: r3d_18
    input_channels: 3
    loss_function: MAE
    lr: 1e-3
    lr_patience: 5

  #### CALLBACKS ####
  callbacks:
    model_checkpoint:
      monitor: "val_loss" # name of the logged metric which determines when model is improving
      mode: "min" # can be "max" or "min"
      save_top_k: 1 # save k best models (determined by above metric)
      save_last: False # additionally, always save model from last epoch
      verbose: True
      dirpath: "checkpoints/"
      filename: "epoch_{epoch:03d}"
      auto_insert_metric_name: False
    early_stopping:
      monitor: "val_loss" # name of the logged metric which determines when model is improving
      mode: "min" # can be "max" or "min"
      patience: 20 # how many validation epochs of not improving until training stops
      min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement

  #### DATA ####
  datamodule:
    augment: True
    image_size: [ 384, 384 ]
    image_mean: [ 0.43216, 0.394666, 0.3764 ]
    image_std: [ 0.22803, 0.22145, 0.21698 ]
    batch_size: 32
    workers: 6
    sun_mask: False
    blur_mask: False
