convert_timestamps:
  script_path: scripts/convert_timestamps.py
  output_path: data/Prepared/images

clean_dataframe:
  script_path: scripts/clean_dataframe.py
  output_path: data/Prepared/cleaned_irradiance.csv

export_periods:
  script_path: scripts/export_periods.py
  time_window: 15
  history_size: 4
  output_path: data/Prepared/periods.pickle

export_eval_periods:
  script_path: scripts/export_eval_periods.py
  output_path: data/Eval

train_forecaster:
  script_path: scripts/train_forecaster.py
  seed: 42

  #### MODE ####
  debug: False
  test_only: False

  restore_from_ckpt:

  export:
    export_to_onnx: False
    opset: 15
    use_simplifier: False

  #### TRAINER ####
  trainer:
    devices: 1
    precision: bf16-mixed
    min_epochs: 10
    max_epochs: 20

  #### MODEL ####
  model:
    model_name: r3d_18
    compile: False
    loss_function: BerHu
    lr: 3e-4
    lr_patience: 3

  #### CALLBACKS ####
  callbacks:
    model_checkpoint:
      monitor: "val_loss" # name of the logged metric which determines when model is improving
      mode: "min" # can be "max" or "min"
      save_top_k: 1 # save k best models (determined by above metric)
      save_last: False # additionally, always save model from last epoch
      verbose: True
      dirpath: "checkpoints/"
      filename: "epoch_{epoch:03d}"
      auto_insert_metric_name: False
    early_stopping:
      monitor: "val_loss" # name of the logged metric which determines when model is improving
      mode: "min" # can be "max" or "min"
      patience: 5 # how many validation epochs of not improving until training stops
      min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement

  #### DATA ####
  datamodule:
    augment: False
    train_val_set_size: 1.0 # size of the train and validation sets for experiments in relation to overall size; 0-1 range
    image_size: [ 128, 128 ]
    image_mean: [ 0.43216, 0.394666, 0.3764 ]
    image_std: [ 0.22803, 0.22145, 0.21698 ]
    batch_size: 64
    workers: 32
    add_sun_mask: True
    add_irradiance_channel: True
    cloud_mask_method: null # available: null, blue_red_ratio, blue_red_difference, normalized_blue_red_ratio
    optical_flow: null # available: null, dis, farneback, deep_flow, pca_flow, dual_tvl1, dense_rlof
