convert_timestamps:
  script_path: scripts/convert_timestamps.py
  output_path: data/prepared/images

clean_dataframe:
  script_path: scripts/clean_dataframe.py
  output_path: data/prepared/cleaned_irradiance.csv

export_periods:
  script_path: scripts/export_periods.py
  time_window: 15   # target forecasting horizon in minutes
  time_shift: 5     # minutes between history samples
  history_size: 4   # used history samples
  output_path: data/prepared/periods.pickle

export_eval_periods:
  script_path: scripts/export_eval_periods.py
  output_path: data/eval

train_forecaster:
  script_path: scripts/train_forecaster.py
  seed: 42

  #### MODE ####
  debug: False
  test_only: False

  restore_from_ckpt:

  export:
    export_to_onnx: False
    opset: 17

  #### TRAINER ####
  trainer:
    devices: 1
    precision: bf16-mixed
    min_epochs: 10
    max_epochs: 30

  #### MODEL ####
  model:
    model_name: resnet50
    pretrained: True
    compile: False
    loss_function: BerHu
    lr: 3e-4
    lr_patience: 5

  #### CALLBACKS ####
  callbacks:
    model_checkpoint:
      monitor: "val_loss" # name of the logged metric which determines when model is improving
      mode: "min" # can be "max" or "min"
      save_top_k: 1 # save k best models (determined by above metric)
      save_last: False # additionally, always save model from last epoch
      verbose: True
      dirpath: "checkpoints/"
      filename: "epoch_{epoch:03d}"
      auto_insert_metric_name: False
    early_stopping:
      monitor: "val_loss" # name of the logged metric which determines when model is improving
      mode: "min" # can be "max" or "min"
      patience: 10 # how many validation epochs of not improving until training stops
      min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement

  #### DATA ####
  datamodule:
    augment: True
    train_val_set_size: 1.0 # size of the train and validation sets for experiments in relation to overall size; 0-1 range
    image_size: [ 128, 128 ]
    image_mean: [ 0.485, 0.456, 0.406 ]
    image_std: [ 0.229, 0.224, 0.225 ]
    batch_size: 128
    workers: 16
    add_sun_mask: True
    add_irradiance_channel: True
    cloud_mask_method: normalized_blue_red_ratio # available: null, red_blue_ratio, red_blue_difference, normalized_blue_red_ratio
    optical_flow: dis # available: null, dis, farneback, deep_flow, pca_flow, dual_tvl1, dense_rlof
